name: protchem
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - tensorflow=2.12
  - keras
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - biopython
  - rdkit
  - tqdm
  - pip:
      - transformers==4.31.0
      - tokenizers==0.13.3